"Enable Combat" = true
"Enable Experience" = false
"Enable Hunger & Health" = true
"Enable Items" = true
"Enable Mining" = true
"Enable Miscellaneous" = true
"Enable Mobs" = true
"Enable Movement" = true
"Enable Sleep & Respawn" = true
"Enable World" = true

[World]
	#Change a few things relative to Serene Seasons
	"Enable Seasons" = true
	#Changes ore generation of many ores. Also adds poor and rich Iron, Gold and Copper
	"Enable Ore Generation" = false
	"Enable Coal & Charcoal" = true

	#Change a few things relative to Serene Seasons
	[World.Seasons]
		#Removes greenhouse glass.
		"No greenhouse glass" = true
		#Saplings no longer drop in Winter.
		"No Saplings in Winter" = true
		#Grass and tall grass decays in Winter and regrows back in Spring. Saplings are also transformed into Dead Bushes.
		"Grass Decay and Growth" = true
		#Makes the following changes to Serene Seasons config:
		#Makes the following changes to Serene Seasons config:
		#* seasonal_crops is set to false, as it's controlled by Plants Growth
		#* Sets the starting season to mid summer
		#
		"Serene Seasons changes" = true
		#How many minutes will day and night duration be shifted based off seasons? E.g. in Mid spring / autumn the duration of day and night is vanilla, when moving off those seasons day and night will last this many minutes more/less. In mid summer / winter the duration of day and night duration will be more / less by 3 times this value.
		#Range: 0.0 ~ 3.0
		"Time Control day night shift" = 1.0
		"Season based fishing time" = true
		#Chance for a bone meal to fail to grow something. Empty this string to disable. Accepts a list of seasons and chances separated by a ;
		"Bone meal fail chance" = "AUTUMN,0.4;WINTER,0.8"

	#Changes ore generation of many ores. Also adds poor and rich Iron, Gold and Copper
	[World."Ore Generation"]
		#Enables a Data Pack that changes Iron, Gold and Copper generation to include Poor and Rich Ores.
		"Poor and Rich Ore Generation" = true

	[World."Coal & Charcoal"]
		#Chance for logs to release charcoal layer when burnt
		#Range: 0.0 ~ 1.0
		"Charcoal from burnt logs chance" = 0.8
		#If enabled, a data pack will be enabled that removes the Charcoal recipe from smelting and makes Coal Ore require an Iron Pickaxe or better to mine.
		"No charcoal smelting and iron coal" = false

		[World."Coal & Charcoal"."Two flint fire starter"]
			#If true, two flints (on per hand) can start a fire
			Enabled = true
			#Chance to ignite a block when using two flints
			#Range: 0.0 ~ 1.0
			"Ignite Chance" = 0.35
			#Chance for the flint to break when using two flints
			#Range: 0.0 ~ 1.0
			"Break Chance" = 0.3

["Sleep & Respawn"]
	#Generate Respawn Obelisks around the world where a precise respawn can be set
	"Enable Respawn Obelisk" = true
	#Zombies drop cloth instead of Rotten Flesh. Cloth is used to make beds and various other stuff.
	"Enable Cloth" = true

	#Zombies drop cloth instead of Rotten Flesh. Cloth is used to make beds and various other stuff.
	["Sleep & Respawn".Cloth]
		#Enables a Data Pack that makes zombies drop cloth instead of rotten flesh and beds require Cloth to be crafted.
		"Data Pack" = true

[Movement]

	[Movement.Minecarts]
		#If true, enables a data pack that makes rails cheaper and adds recipes for new rails.
		"Data Pack" = true

[Mobs]
	#Changes to mob spawn
	"Enable Spawning" = true
	#Changes to EnhancedAI config
	"Enable EnhancedAI" = true
	#Increase monsters health, movement speed, etc. This feature uses Mobs Properties Randomness.
	"Enable Stats Buffs" = true

	#Changes to mob spawn
	[Mobs.Spawning]
		#Animals and Sea Creatures can no longer naturally spawn in Winter and will spawn less in autumn.
		"Animals and sea creature in cold seasons" = true

		[Mobs.Spawning.Despawning]
			#Despawn Distance on winter, note that lower values increase the mobs around the player.
			#Range: > -2147483648
			Winter = 96
			#Despawn Distance on spring, note that lower values increase the mobs around the player.
			#Range: > -2147483648
			Spring = 128
			#Despawn Distance on summer, note that lower values increase the mobs around the player.
			#Range: > -2147483648
			Summer = 128
			#Despawn Distance on autumn, note that lower values increase the mobs around the player.
			#Range: > -2147483648
			Autumn = 128

		[Mobs.Spawning."Hostile Cap"]
			#Hostile Mobs cap on winter, note that lower values increase the mobs around the player.
			#Range: > -2147483648
			Winter = 40
			#Hostile Mobs cap on spring, note that lower values increase the mobs around the player.
			#Range: > -2147483648
			Spring = 70
			#Hostile Mobs cap on summer, note that lower values increase the mobs around the player.
			#Range: > -2147483648
			Summer = 100
			#Hostile Mobs cap on autumn, note that lower values increase the mobs around the player.
			#Range: > -2147483648
			Autumn = 70

	#Increase monsters health, movement speed, etc. This feature uses Mobs Properties Randomness.
	[Mobs."Stats Buffs"]
		#Enables a Data Pack that buffs mobs.
		"Enable DataPack" = true

[Miscellaneous]
	#Various data packs that can be enabled/disabled
	"Enable Data Packs" = true

	#Various data packs that can be enabled/disabled
	[Miscellaneous."Data Packs"]
		#If true, no integrated data pack will be loaded
		"Disable ALL data packs" = false
		#Enables a Data Pack that overhauls advancements to make them work with IguanaTweaks.
		Advancements = true
		#Enables a data pack that changes all the item stats
		"Item Stats Data Pack" = true
		#If true a data pack will be enabled that overhauls structure loot. This overrides some loot tables from ITR
		"Better Structure Loot" = true
		#If true, a data pack is enabled that changes the growth of plants based off seasons
		"Plant growth multipliers data pack" = true
		#Enables a data pack that slows down growing, breeding, egging etc based off seasons
		"Livestock Data" = true

[Mining]
	#Add a new Netherite alternative which makes you go fast
	"Enable Keego" = true
	#Add new multi block furnaces
	"Enable Multi Block Furnaces" = true
	"Enable Forging" = true
	#Add Soul Steel, a new metal made by alloying Iron, Soul Sand and Hellish Coal
	"Enable Soul Steel" = true
	#Add Quaron, a new metal made by alloying Iron and Amethyst
	"Enable Quaron" = true
	#Add Durium, a new metal made by alloying Durium Scrap (found as scrap pieces in ores in the Overworld) and can be used to upgrade Iron Equipment
	"Enable Durium" = true
	#Adds mining charge
	"Enable Mining Charge" = true

	#Add new multi block furnaces
	[Mining."Multi Block Furnaces"]
		#Enables a data pack that changes the vanilla Blast Furnace recipe to give the multi block blast furnace.
		"Blast Furnace Data pack" = true

	[Mining.Forging]
		#Enchanted items can't be forged
		"Unforgable enchanted items" = true
		#Enables the following changes to vanilla data pack:
		#* All metal gear requires a forge to be made
		#* Diamond Gear requires Gold gear to be forged
		#* Gold Gear requires Flint / Leather gear to be forged
		#* Iron Gear requires Stone / Chained Copper gear to be forged
		#* Buckets, Flint and Steel and Shears require a forge to be made
		"Forging Equipment Crafting Data Pack" = true

	#Add Durium, a new metal made by alloying Durium Scrap (found as scrap pieces in ores in the Overworld) and can be used to upgrade Iron Equipment
	[Mining.Durium]
		#Enables a data pack that makes Lodestone require Durium instead of Netherite.
		"Durium Lodestone" = true

[Items]
	#A new block that can let you carry more stuff around.
	"Enable Crate" = true
	#Add Solarium, a new metal made by alloying Overgrown solium moss ball (found in hot biomes) and can be used to upgrade Iron Equipment
	"Enable Solarium" = true
	#Back to base
	"Enable Recall Potion" = false
	#Check your altitude
	"Enable Altimeter" = true
	#Add flint tools and shield.
	"Enable Flint Expansion" = false
	#Add Chained Copper Armor
	"Enable Chained Copper Armor" = false
	#Add a new explosive block.
	"Enable Explosive Barrel" = true
	#Two new set of tools
	"Enable Copper Tools Expansion" = true
	#Integration with Tool Belt
	"Enable ToolBelt" = true

	#A new block that can let you carry more stuff around.
	[Items.Crate]
		#Range: > 0
		"Max crates without slowdown" = 1
		#When you have > 'Max crates without slowdown' this is the base value for the slowdown. The slowdown is calculated as (crates above 'Max crates' * this * crates above 'Max crates')
		#Range: 0.0 ~ 1.0
		"Base Slowness per crate over max" = 0.05

	#Check your altitude
	[Items.Altimeter]
		"Show approx altitude in tooltip" = true

	#Integration with Tool Belt
	[Items.ToolBelt]
		#Enables a data pack that changes the crafting of the Tool Belt to give more slots (2 -> 4). Also makes the cost to upgrade start from 4 instead of 2
		"Bigger ToolBelt" = true

["Hunger & Health"]
	#Adds new foods and drinks.
	"Enable New Foods & Drinks" = true

[Experience]
	#Adds a brand new enchanting table. If this feature is enabled a data pack is also enabled that changes the enchanting table recipe. Items in iguanatweaksexpanded:not_enchantable tag cannot be enchanted.
	"Enable Enchanting" = true
	#Change some enchantments related stuff and adds new enchantments. Please note that Damaging enchantments such as water coolant are enabled only if ITR 'Replace damaging enchantments' is enabled. This also applies for protection enchantments and ITR 'Replace protection enchantments'
	"Enable New Enchantments" = true

	#Adds a brand new enchanting table. If this feature is enabled a data pack is also enabled that changes the enchanting table recipe. Items in iguanatweaksexpanded:not_enchantable tag cannot be enchanted.
	[Experience.Enchanting]
		#Enchanted items can no longer be merged with other enchanted items (also applies to enchanted books).
		"No enchantment merge" = true
		#Enchanted items can no longer be upgraded (e.g. netherite)
		"No enchanted smithing" = true
		#If true, grindstone will give XP based off the new enchanting table. This is based off the ITR levelScalingFormula set to a fixed value
		"Better grindstone xp" = false

[Combat]
	#Gives a use to the fletching table.
	"Enable Fletching table" = true
	#Changes to Shields+.
	"Enable Shields+" = true

	#Gives a use to the fletching table.
	[Combat."Fletching table"]
		#Enables the following changes:
		#* Replaces the vanilla fletching table recipe with the mod's one
		#* Adds more arrows recipes
		"Fletching Data Pack" = true

	#Changes to Shields+.
	[Combat."Shields+"]
		#Changes the crafting recipes of metal shields to require a Forge and rebalances the shields.
		"Shields+ Compat DataPack" = true

