
["Shields+"]
	#In vanilla when you start blocking with a shield, there's a 0.25 seconds (5 ticks) window where you are still not blocking. By default the windup is removed.
	#Range: > 0
	"Shield Windup" = 0
	#If true shields will block only a certain amount of damage. If false the vanilla behaviour is used.
	"Shields Block Fixed Damage Amount" = true
	#The minimum damage dealt to the player for the shield to take damage. Vanilla is 3. E.g. With this set to 3, the shield will not be damaged if damage received is lower than.
	#Range: 0.0 ~ 3.4028234663852886E38
	"Min Shield Hurt Damage" = 0.0
	#Makes shields always disable for 1.6 seconds like Combat Test snapshots.
	"Combat Test shield disabling" = true
	#If true, shields can be lifted only for a certain amount of time and will go on cooldown.
	"Lifted and Cooldown" = true

